- name: Deploy example service
  copy:
    src: example.service
    dest: /etc/systemd/system/example.service
    mode: '0644'

- name: Enable and start example service
  systemd:
    name: example.service
    state: started
    enabled: yes

